[package]
name = "poc_quarks"
version = "0.1.0"
authors = ["othelarian <le.maitre.killian@gmail.com>"]
edition = "2018"

[dependencies]
candelabre-windowing = "0.2.0"
gl = "0.14.0"
glutin = "0.24.0"
nvg = "0.5.9"
nvg-gl = "0.5.4"
